channels:
  - conda-forge
dependencies:
  - r-base=4.1
  - r-tidyverse
  - r-shiny
  - r-shinythemes
  - r-dt
  - r-shinycssloaders
  - r-foreign
  - r-shinyjs
  - r-shinydashboard
  - r-haven
  - r-caret
  - r-randomforest
  - r-nnet
  - r-mass
  - r-kernlab
  - r-car
  - r-psych
  - r-ggplot2
  - r-dplyr
  - r-gparotation
  - r-reshape2